version: '3'
services:
  libreclinica-qa:
    build: 
      context: .
      dockerfile: Dockerfile
    image: libreclinica-qa
    environment:
      - CONFLUENCE_USERNAME=$(CONFLUENCE_USERNAME)
      - CONFLUENCE_ACCESS_TOKEN=$(CONFLUENCE_ACCESS_TOKEN)
      - CONFLUENCE_SPACE_ID=$(CONFLUENCE_SPACE_ID)
      - LC_ROOT_USERNAME=${LC_ROOT_USERNAME}
      - LC_ROOT_PASSWORD=${LC_ROOT_PASSWORD}
    container_name: libreclinica-qa
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./tests:/app/tests
      - ./app:/app
      - ./allure-results:/allure-results
  
  allure-reports-server:
    build: 
      context: ./allure-service # Build the image from allure-service dir
    image: allure-reports-server
    container_name: allure-reports-server
    depends_on:
      - libreclinica-qa
    ports:
      - "8186:5050"
    volumes:
      - ./allure-results:/allure-results

volumes:
  allure-results:
